#include <stdio.h>
#include <stdbool.h>
#include <time.h>
#include <memory.h>
#include "csha256.h"

extern void asm_sha256_calc(uint32_t *hash, uint8_t *data, size_t len);

/// @return true if test passed. false otherwise.
bool sha256_unit_test();

int main(){
    char msg[] = "admin123";
    uint32_t hash[8] = { 0 };

    printf("sha256 unit test: %s\n", sha256_unit_test() ? "passed" : "failed");

    printf("msg[%zu]: %s\n", sizeof(msg)-1,  msg);

    asm_sha256_calc(hash, (uint8_t*)msg, sizeof(msg) - 1);
    printf("asm: %08x%08x%08x%08x%08x%08x%08x%08x\n", hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7]);

    csha256_calc(hash, (uint8_t*)msg, sizeof(msg) - 1);
    printf("  C: %08x%08x%08x%08x%08x%08x%08x%08x\n", hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7]);
    return 0;
}

bool sha256_unit_test(){
    uint8_t msg[130] = "\0";
    uint32_t hasha[8];
    uint32_t hashc[8];

    // TEST 1 - comparison with hashes generated by https://emn178.github.io/online-tools/sha256.html
    const char *messages[] = {
        "password",
        "passWoRd123456789ABCdEFGHIJkLMNOPQRSTUVWXyZabcdefghijklm",
        "pa$sworD123456789ABCDEfGHIJKLMNOPQRSTUVWxYZabcdefghijklmn",
        "Pas$word123456789ABCdEFGHiJKLMNOPQRSTUVwXYZabcdefghijklmnoprstuv",
        "Pa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabcdefghijklmnoprstuvw",
        "Pa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabcdefghijklmnoprstuvwPa%$word1234567ABCdefGHiQRSTUVwXYZabcdefghijklmnoprstuvw",
        "pA%$word212456789ABCdefGHiJKLMNOPQRSTUVwXYZabcdefghijklmnoprstuvwPa%$word1234567ABCdefGHiQRSTUVwXYZabcdefghijklmnoprstuvwg",
        "Pa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabcdefghijklmnoprstuvwPa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabefghijklmnoprstuvw",
        "Pa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabcdefghijklmnopdrstuvwPa%$word123456789ABCdefGHiJKLMNOPQRSTUVwXYZabefghijklmnoprstuvw",
    };
    uint32_t correct_hashes[sizeof(messages)/sizeof(messages[0])][8] = {
        { 0x5e884898, 0xda280471, 0x51d0e56f, 0x8dc62927, 0x73603d0d, 0x6aabbdd6, 0x2a11ef72, 0x1d1542d8 },
        { 0x9a14157a, 0xc50d12b1, 0xea8b7b92, 0x723a40ae, 0xa4c78e30, 0x50bb8c62, 0x71fdfa8f, 0x713edccd },
        { 0x0fd9e068, 0xde71f71c, 0x348bbae1, 0xecda9308, 0x73a9b6fc, 0xee739ea3, 0xf0a495ef, 0x565b52ed },
        { 0x3e5a3606, 0x93297c30, 0xc799d3fd, 0xa7a2a3bc, 0x804143eb, 0xa56539a0, 0x0f7c6544, 0x3d3d4d06 },
        { 0xe50ddc4f, 0xd8e0b2bf, 0x5b3f1b8b, 0x112dab0a, 0x2c98582f, 0x18dbac7e, 0x955da321, 0xb6b60b90 },
        { 0x1ee86ab9, 0xaaad4510, 0x128eda69, 0x3a9d8d8f, 0xdcf90de3, 0xf53daf89, 0x8c8fe97c, 0xee0b5786 },
        { 0x9e32302b, 0xa26ab281, 0xb1b961e7, 0xb7ef33b5, 0x2bbea892, 0xce3cf66a, 0x366a9b0c, 0x4cc2f98b },
        { 0xf85b68ec, 0x24cd62c5, 0x09d74c34, 0xa84da5fe, 0x1817999e, 0x6acff81e, 0xee2d4c3e, 0xa671db71 },
        { 0xd0c9e9bf, 0x9365d791, 0x55c8eb40, 0x1a306553, 0x4c31e089, 0x954193e0, 0x5a0799cb, 0x6b1f322e },
    };

    for(int i = 0; i < sizeof(messages)/sizeof(messages[0]); i++){
        csha256_calc(hasha, (uint8_t*)messages[i], strlen(messages[i]));
        if(memcmp(hasha, correct_hashes[i], sizeof(hasha)) != 0){
            fprintf(stderr, "sha256 unit test 1 failed at %d\n", i);
            return false;
        }
    }

    // TEST 2 - comparison C and ASM implementation
    srand(time(NULL) * clock());
    for (size_t i = 0; i < sizeof(msg)-1; i++){
        msg[i] = (char)(rand() % 256);
    }

    for(size_t i = 1; i < sizeof(msg)-1; i++){
        asm_sha256_calc(hasha, (uint8_t*)msg, i);
        csha256_calc(hashc, (uint8_t*)msg, i);
        if(memcmp(hasha, hashc, sizeof(hasha)) != 0){
            fprintf(stderr, "sha256 unit test 2 failed at %zu\n", i);
            return false;
        }
    }

    return true;
}